// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import Foundation

/// Static serialization behavior for one exact target type.
///
/// A self-provided type uses itself as `Target`, including an external type
/// with an intentional retroactive conformance. A separately provided
/// structural or custom serializer names another target type. Serializer
/// declarations are type-level behavior and are never instantiated by Fory.
public protocol Serializer {
    /// The exact value type read and written by this serializer.
    associatedtype Target

    static var staticTypeId: TypeId { get }
    static var isNullableType: Bool { get }
    static var isRefType: Bool { get }
    static var isWrapper: Bool { get }

    static func isNone(_ value: Target) -> Bool
    static func defaultValue(_ context: ReadContext) throws -> Target

    static func writeData(_ value: Target, _ context: WriteContext) throws
    static func readData(_ context: ReadContext) throws -> Target

    static func write(
        _ value: Target,
        _ context: WriteContext,
        refMode: RefMode,
        writeTypeInfo: Bool
    ) throws

    static func read(
        _ context: ReadContext,
        refMode: RefMode,
        readTypeInfo: Bool
    ) throws -> Target

    static func writeTypeInfo(_ context: WriteContext) throws
    static func readTypeInfo(_ context: ReadContext) throws -> TypeInfo?
}

/// Structural schema behavior generated by `@ForyStruct`, `@ForyEnum`, and
/// `@ForyUnion`.
public protocol StructSerializer: Serializer {
    static var foryEvolving: Bool { get }

    static func foryFieldsInfo(trackRef: Bool) -> [TypeMeta.FieldInfo]

    /// Builds field metadata after all serializer registrations are visible to the resolver.
    /// Serialization and deserialization hot paths must use finalized TypeInfo metadata instead.
    static func foryFieldsInfo(
        trackRef: Bool,
        resolveSerializerTypeId: (Any.Type) throws -> TypeId
    ) throws -> [TypeMeta.FieldInfo]

    static func readCompatible(
        _ context: ReadContext,
        typeInfo: TypeInfo
    ) throws -> Target
}

public extension Serializer {
    @inlinable
    static var isNullableType: Bool { false }

    @inlinable
    static var isRefType: Bool { false }

    @inlinable
    static var isWrapper: Bool { false }

    @inlinable
    static func isNone(_: Target) -> Bool { false }

    static func defaultValue(_: ReadContext) throws -> Target {
        throw unsupportedDefaultValue(Self.self)
    }

    @inlinable
    static func write(
        _ value: Target,
        _ context: WriteContext,
        refMode: RefMode,
        writeTypeInfo: Bool
    ) throws {
        if refMode != .none {
            if refMode == .tracking, isRefType {
                let object = value as AnyObject
                if context.refWriter.tryWriteRef(buffer: context.buffer, object: object) {
                    return
                }
            } else {
                context.buffer.writeInt8(RefFlag.notNullValue.rawValue)
            }
        }

        if writeTypeInfo {
            try Self.writeTypeInfo(context)
        }
        try Self.writeData(value, context)
    }

    @inlinable
    static func read(
        _ context: ReadContext,
        refMode: RefMode,
        readTypeInfo: Bool
    ) throws -> Target {
        switch refMode {
        case .none:
            return try readValueData(context, readTypeInfo: readTypeInfo)
        case .nullOnly:
            let rawFlag = try context.buffer.readInt8()
            switch rawFlag {
            case RefFlag.null.rawValue:
                return try Self.defaultValue(context)
            case RefFlag.notNullValue.rawValue:
                return try readValueData(context, readTypeInfo: readTypeInfo)
            case RefFlag.refValue.rawValue:
                let reservedRefID = context.trackRef ? context.refReader.reserveRefID() : nil
                let value = try readValueData(context, readTypeInfo: readTypeInfo)
                if let reservedRefID {
                    context.refReader.storeRef(value, at: reservedRefID)
                }
                return value
            case RefFlag.ref.rawValue:
                let refID = try context.buffer.readVarUInt32()
                return try context.refReader.readRef(refID, as: Target.self)
            default:
                throw invalidRefFlag(rawFlag)
            }
        case .tracking:
            let rawFlag = try context.buffer.readInt8()
            guard let flag = RefFlag(rawValue: rawFlag) else {
                throw invalidRefFlag(rawFlag)
            }
            switch flag {
            case .null:
                return try Self.defaultValue(context)
            case .ref:
                let refID = try context.buffer.readVarUInt32()
                return try context.refReader.readRef(refID, as: Target.self)
            case .refValue:
                let reservedRefID = context.trackRef ? context.refReader.reserveRefID() : nil
                let value = try readValueData(context, readTypeInfo: readTypeInfo)
                if let reservedRefID {
                    context.refReader.storeRef(value, at: reservedRefID)
                }
                return value
            case .notNullValue:
                return try readValueData(context, readTypeInfo: readTypeInfo)
            }
        }
    }

    @inlinable
    @inline(__always)
    static func writeTypeInfo(_ context: WriteContext) throws {
        guard staticTypeId.isUserTypeKind else {
            context.writeStaticTypeInfo(staticTypeId)
            return
        }
        try context.typeInfo(for: Self.self).writeTypeInfo(context)
    }

    static func readTypeInfo(_ context: ReadContext) throws -> TypeInfo? {
        try context.readTypeInfo(for: Self.self)
    }

    @inlinable
    @inline(__always)
    internal static func readValueData(
        _ context: ReadContext,
        readTypeInfo: Bool
    ) throws -> Target {
        let typeInfo =
            readTypeInfo
            ? try Self.readTypeInfo(context)
            : context.getTypeInfo(for: Self.self)
        return try context.withTypeInfo(typeInfo, for: Self.self) {
            try Self.readData(context)
        }
    }
}

public extension StructSerializer {
    @inlinable
    static var foryEvolving: Bool { true }

    @inlinable
    static func foryFieldsInfo(trackRef _: Bool) -> [TypeMeta.FieldInfo] {
        []
    }

    @inlinable
    static func foryFieldsInfo(
        trackRef: Bool,
        resolveSerializerTypeId _: (Any.Type) throws -> TypeId
    ) throws -> [TypeMeta.FieldInfo] {
        foryFieldsInfo(trackRef: trackRef)
    }
}

@inline(never)
private func unsupportedDefaultValue<S: Serializer>(_ serializer: S.Type) -> ForyError {
    ForyError.invalidData("\(serializer) does not define a default target value")
}

@usableFromInline
@inline(never)
internal func invalidRefFlag(_ rawFlag: Int8) -> ForyError {
    ForyError.refError("invalid ref flag \(rawFlag)")
}
