# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "fory-rust-local-benchmarks"
version.workspace = true
edition.workspace = true

[[bench]]
name = "external_type_bench"
path = "benches/external_type_bench.rs"
harness = false

[[bench]]
name = "buffer_write_bench"
path = "benches/buffer_write_bench.rs"
harness = false

[[bench]]
name = "buffer_read_bench"
path = "benches/buffer_read_bench.rs"
harness = false

[[bench]]
name = "threaded_bench"
path = "benches/threaded_bench.rs"
harness = false

[dependencies]
criterion = "0.5"
fory = { path = "../../../rust/fory" }
fory-core = { path = "../../../rust/fory-core" }
fory-derive = { path = "../../../rust/fory-derive" }
fory-external-model = { path = "../../../rust/api-tests/external-model" }
